# ============================
# 1️⃣ Build stage
# ============================
FROM node:22.4-alpine AS builder

ARG DATABASE_USER
ARG DATABASE_NAME_SCHEDULE
ARG DATABASE_URL_SCHEDULE
ARG DATABASE_PASSWORD

WORKDIR /usr/src/app

# Install OpenSSL (required for Prisma on Alpine)
RUN apk add --no-cache openssl

# Copy package files
COPY package*.json ./

# Copy shared libraries and Prisma schema
COPY libs ./libs
COPY apps/scheduler-service/src/infrastructure/prisma ./prisma

# Install dependencies (including dev)
RUN npm install

# Copy all remaining source code and workspace configs
COPY . .
COPY tsconfig.json nest-cli.json ./

# Set environment variables for database configuration
ENV DATABASE_URL_SCHEDULE=${DATABASE_URL_SCHEDULE}
ENV DATABASE_USER=${DATABASE_USER}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV DATABASE_NAME_SCHEDULE=${DATABASE_NAME_SCHEDULE}

# Generate Prisma client (ensure correct binary for Alpine)
RUN npx prisma generate --schema=apps/scheduler-service/src/infrastructure/prisma/schema.prisma

# Build the NestJS app
RUN npx nest build scheduler-service

# ============================
# 2️⃣ Production stage
# ============================
FROM node:22.4-alpine AS production

WORKDIR /usr/src/app

# Install OpenSSL for runtime
RUN apk add --no-cache openssl

# Copy package files from builder
COPY --from=builder /usr/src/app/package*.json ./

# Install  dependencies
RUN npm install 

# Copy built files and assets
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/libs ./libs

# Copy generated Prisma client and engines
# Make sure the folder name matches the one in your schema.prisma

COPY --from=builder /usr/src/app/apps/scheduler-service/src/infrastructure/generated/scheduler-service ./apps/scheduler-service/src/infrastructure/generated/scheduler-service
COPY --from=builder /usr/src/app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /usr/src/app/node_modules/@prisma ./node_modules/@prisma

# Set production environment variables
ENV NODE_ENV=production
ENV PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1

# Expose service port
EXPOSE ${Port}

# Start the application
CMD ["node", "dist/apps/scheduler-service/main"]
