# ============================
# 1️⃣  Base build stage
# ============================
FROM node:20-alpine AS builder

WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

COPY libs ./libs

# Install all deps for build
RUN yarn 

# Copy source code and envs
COPY . .
# Copy prisma env
COPY apps/task-service/src/infrastructure/prisma/.env ./src/infrastructure/prisma/.env

COPY tsconfig.json nest-cli.json ./
# Build NestJS app
RUN npm run build

# ============================
# 2️⃣  Production stage
# ============================
FROM node:20-alpine AS production

WORKDIR /usr/src/app

# Copy dist and required files from builder
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/src/infrastructure/prisma/.env ./src/infrastructure/prisma/.env

# Install only production dependencies
RUN npm ci --omit=dev

# Copy root env for runtime
COPY apps/task-service/.env .env

# Expose app port
EXPOSE ${PORT}

# Default command
CMD ["node", "dist/main"]
